version: 2.1
orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@2.0.0
jobs:
  build-and-test:
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          post-steps:
            - run: heroku-postbuild
          pre-steps:
            - run: npm run build
            -
